server:
  port: 9196
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SuperAdminDB
    username: root
    password: riddhi1509
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true