server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:4000/UserManagementDB
    username: root
    password: mqpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: RadVeda.Team@gmail.com
    password: ozrcyamdmydhelbi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: 8fafe408a14b81c3e649253fa8ebdc7c01a64a361fec74cc8903e2febdd2cac1
    jwtExpirationInMs: 1800000
